server:
  port: 8085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-map
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.11:3306/service-map?characterEncoding=utf-8&serverTimezne=GMT%2B8
    username: root
    password: 123456

# 自定义的放在后面
amap:
  key: fac7e9d39088e3e11b36a56c3671ad69
  # 服务id  服务名称：测试服务3
  sid: 883396