server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-passenger
  redis:
    host: 192.168.1.31
    port: 6379
    database: 0
logging:
  level:
    com.baomidou.mybatisplus: debug