server:
  port: 8086

spring:
  application:
    name: service-driver-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/service_driver_user?characterEncoding=utf-8&serverTimezne=GMT%2B8
    username: root
    password: Chen8482332.
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml