
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/service_order?characterEncoding=utf-8&serverTimezne=GMT%2B8
    username: root
    password: Chen8482332.
  redis:
    host: 192.168.1.31
    port: 6379
    database: 0

logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

---
spring:
  profiles: 8089
server:
  port: 8089
---
spring:
  profiles: 8090
server:
  port: 8090