server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.11:3306/service-order?characterEncoding=utf-8&serverTimezne=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 192.168.182.30
    port: 6379
    database: 0